import type { Metadata } from 'next'
import { MarketingShell } from '@/components/marketing/MarketingShell'
import { Section, P, UL, LI, Updated } from '@/components/legal/LegalDoc'

export const metadata: Metadata = {
  title: 'Terms of Service · Locuta',
  description: 'The terms that govern your use of Locuta.',
}

export default function TermsPage() {
  return (
    <MarketingShell
      eyebrow="Legal"
      title="Terms of Service"
      subtitle="The agreement between you and Locuta when you use the service."
    >
      <div style={{ maxWidth: 760 }}>

        <Section n="1" title="Agreement to these terms">
          <P>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of Locuta&apos;s
            website, app, and services (the &ldquo;Service&rdquo;). By creating an account or using the
            Service, you agree to these Terms. If you do not agree, please do not use Locuta.
          </P>
        </Section>

        <Section n="2" title="The service">
          <P>
            Locuta is an AI-powered platform for practising English speaking and communication. You record
            short speaking exercises; we transcribe, analyse, and score them, and provide feedback and
            example answers. Feedback is generated by automated systems and is intended to help you
            practise — it is not professional, academic, or certification advice.
          </P>
        </Section>

        <Section n="3" title="Your account">
          <UL>
            <LI>You must provide accurate information and keep your login credentials secure.</LI>
            <LI>You are responsible for activity that happens under your account.</LI>
            <LI>You must be old enough to use the Service in your country (at least 13, or higher where required).</LI>
            <LI>Notify us promptly if you believe your account has been compromised.</LI>
          </UL>
        </Section>

        <Section n="4" title="Acceptable use">
          <P>When using Locuta, you agree not to:</P>
          <UL>
            <LI>Record or upload content that is unlawful, hateful, harassing, or infringes others&apos; rights.</LI>
            <LI>Record other people without their knowledge or consent.</LI>
            <LI>Attempt to disrupt, reverse-engineer, overload, or gain unauthorised access to the Service.</LI>
            <LI>Use the Service to build a competing product or to scrape or resell its content.</LI>
            <LI>Misuse the AI features to generate harmful, deceptive, or abusive content.</LI>
          </UL>
        </Section>

        <Section n="5" title="Your content">
          <P>
            You keep ownership of the recordings and content you create (&ldquo;Your Content&rdquo;). You
            grant Locuta a limited licence to process, store, and display Your Content solely to operate and
            improve the Service for you — for example, to transcribe your audio, generate feedback, and let
            you replay it. We handle Your Content as described in our{' '}
            <a href="/privacy" style={{ color: '#3fb950', fontWeight: 800 }}>Privacy Policy</a>.
          </P>
        </Section>

        <Section n="6" title="Plans, trials, and payments">
          <P>
            Locuta may offer free and paid plans. Where paid plans are available, pricing, billing cycles,
            and trial terms will be shown at the point of purchase and are incorporated into these Terms.
            Unless stated otherwise or required by law, payments are non-refundable. We will give notice of
            changes to pricing that affect you.
          </P>
        </Section>

        <Section n="7" title="Intellectual property">
          <P>
            The Service — including its software, lessons, design, branding, and mascot — belongs to Locuta
            and is protected by law. These Terms do not give you any right to our intellectual property
            except the limited right to use the Service as intended.
          </P>
        </Section>

        <Section n="8" title="Service availability">
          <P>
            We work to keep Locuta available and reliable, but we provide the Service &ldquo;as is&rdquo;
            and cannot guarantee it will always be uninterrupted or error-free. We may update, change, or
            discontinue features over time.
          </P>
        </Section>

        <Section n="9" title="Disclaimers and limitation of liability">
          <P>
            To the fullest extent permitted by law, Locuta is not liable for indirect, incidental, or
            consequential damages arising from your use of the Service, and our total liability is limited
            to the amount you paid us (if any) in the twelve months before the claim. Some jurisdictions do
            not allow certain limitations, so parts of this section may not apply to you.
          </P>
        </Section>

        <Section n="10" title="Termination">
          <P>
            You may stop using Locuta and delete your account at any time. We may suspend or terminate your
            access if you breach these Terms or use the Service in a way that could harm Locuta or other
            users. On termination, the sections that by their nature should survive will continue to apply.
          </P>
        </Section>

        <Section n="11" title="Changes to these terms">
          <P>
            We may update these Terms as the Service evolves. When we make material changes, we will update
            the date above and, where appropriate, notify you. Continuing to use Locuta after changes take
            effect means you accept the updated Terms.
          </P>
        </Section>

        <Section n="12" title="Contact">
          <P>
            Questions about these Terms? Email <strong>info@locuta.in</strong>.
          </P>
        </Section>
      </div>
    </MarketingShell>
  )
}
